### ISSUE TITLE
Using Switch Statement in javascript with syntax error

### ISSUE THREAD

**Issue by ravichittari** [javadelight/delight-nashorn-sandbox#10]
Because of the way interrupt is handled, for Switch statement it fails with syntax errors. 
Can you add this as a test case and see if you can find a solution?

**Comment by objecthub-io** [comment]
That is true. Thanks. Can you try with version 0.0.6 if it works now?

Also, be free to check the regular expressions in [NashornSandboxImpl](https://github.com/javadelight/delight-nashorn-sandbox/blob/master/src/main/xtend/delight/nashornsandbox/internal/NashornSandboxImpl.xtend) line 83ff!

**Comment by mxro** [comment]
Did you get a chance to look at this yet? Otherwise, we'll close the issue soon. Thanks!
