### ISSUE TITLE
Can not use with AdoptOpenJDK 8 due to NoClassDefFoundError Exception being thrown in ThreadMonitor constructor

### ISSUE THREAD

**Issue by smeverts** [javadelight/delight-nashorn-sandbox#107]
When using AdoptOpenJDK 8, the ThreadMonitor can never be initialized and I'm seeing a a NoClassDefFoundError being thrown when the constructor is looking to see if the ThreadMXBean is an instance of com.sun.management.ThreadMXBean.

More specifically, I'm trying to use this within the context of a JEE app server(Wildfly) ... 

Any thoughts on this or am I missing something?

**Comment by smeverts** [comment]
Looks to be that this was an issue with Wildfly being overly restrictive when loading certain modules from it's class loader.  Once I realized this I was able to make the appropriate corrections to the configuration and was able to use the NashornSandbox without any issues.

**Comment by mxro** [comment]
Thank you for reporting / documenting this here. I am sure it will be useful to other's as well!
