### ISSUE TITLE
[Question] UTF-8 support

### ISSUE THREAD

**Issue by desoliture1** [javadelight/delight-nashorn-sandbox#128]
Hey, @javadelight !

I ran into a problem with UTF-8 encoding
For example, let's say we have this code:

```
return ((Invocable) sandbox).invokeFunction(functionName, args)
```

When i pass args in Ukrainian/Turkish/etc, encoded with UTF-8, in the result i have some invalid symbols (like this Ð¿ÑÐ¸Ð²ÑÑ)
Though, when using English it's okay :)

Mine "app" have the UTF-8 encoding support and I've checked the work of this function with this args separately from java and sandbox, in the browser console all working as intended

Is there support for UTF-8 encoding? Or am i missing some set-up settings?...

**Comment by desoliture1** [comment]
I found that my data getting spoiled in "invokeExact" native method in `MethodHandle.class`

**Comment by mxro** [comment]
Thank you for raising this issue!

Does the same script work when using Nashorn without the Sandbox

```
import javax.script.*;

public class EvalScript {
    public static void main(String[] args) throws Exception {
        // create a script engine manager
        ScriptEngineManager factory = new ScriptEngineManager();
        // create a Nashorn script engine
        ScriptEngine engine = factory.getEngineByName("nashorn");
        // evaluate JavaScript statement
        try {
            engine.eval("print('Hello, World!');");
        } catch (final ScriptException se) { se.printStackTrace(); }
```

Could you provide a code example? Thank you!!!

**Comment by desoliture1** [comment]
Sorry for not answering for so long.
I found a cause of the problem, it's in the function which i invoke, not in the nashorn or sandbox
Also, i made a little research - all works fine with UTF-8 symbols (Ukrainian, Turkish, etc)
Thank you for your fast respond and your work!
