### ISSUE TITLE
which version of Javascript it supports?

### ISSUE THREAD

**Issue by Tridu33** [javadelight/delight-nashorn-sandbox#147]
is it support ES5 or further?
i found it can not use `let`, `const` and so on in version `0.3.0`.

**Comment by mxro** [comment]
Thank you for your question. Since this is just around a wrapper around the Nashorn Scripting Engine, the JS version that Nashorn supports will be supported.

See below as per Nashorn documentation:

> The Nashorn engine is an implementation of the [ECMAScript Edition 5.1 Language Specification](http://www.ecma-international.org/publications/standards/Ecma-262.html). It also implements many new features introduced in [ECMAScript 6](http://www.ecma-international.org/ecma-262/6.0/) including template strings; let, const, and block scope; iterators and for..of loops; Map, Set, WeakMap, and WeakSet data types; symbols; and binary and octal literals.

https://docs.oracle.com/javase/9/nashorn/introduction.htm#JSNUG136
