### ISSUE TITLE
dependency problem

### ISSUE THREAD

**Issue by workingDog** [javadelight/delight-nashorn-sandbox#16]
I wanted to use delight-nashorn-sandbox in Scala, but it 
crashes due to the "org.eclipse.xtend#org.eclipse.xtend.lib.gwt;2.8.3" 
as shown in the error below.

I used this in my project.
libraryDependencies += "org.javadelight" % "delight-nashorn-sandbox" % "0.0.8"

I get this error:

Error:Error while importing SBT project:<br/>...<br/><pre>[warn] 	:: org.eclipse.xtend#org.eclipse.xtend.lib;2.8.3: not found
[warn] 	:: org.eclipse.xtend#org.eclipse.xtend.lib.gwt;2.8.3: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.eclipse.xtend:org.eclipse.xtend.lib:2.8.3
[warn] 		  +- org.javadelight:delight-nashorn-sandbox:0.0.8 (/Users/ringo/weblvc/server/mikan-server/build.sbt#L13-22)
[warn] 		  +- mikan:mikan_2.11:1.0-SNAPSHOT
[warn] 		org.eclipse.xtend:org.eclipse.xtend.lib.gwt:2.8.3
[warn] 		  +- org.javadelight:delight-functional:0.0.10
[warn] 		  +- org.javadelight:delight-async:0.1.0
[warn] 		  +- org.javadelight:delight-nashorn-sandbox:0.0.8 (/Users/ringo/weblvc/server/mikan-server/build.sbt#L13-22)
[warn] 		  +- mikan:mikan_2.11:1.0-SNAPSHOT
[trace] Stack trace suppressed: run 'last *:ssExtractProject' for the full output.
[trace] Stack trace suppressed: run 'last *:update' for the full output.
[error] (*:ssExtractProject) sbt.ResolveException: unresolved dependency: org.eclipse.xtend#org.eclipse.xtend.lib;2.8.3: not found
[error] unresolved dependency: org.eclipse.xtend#org.eclipse.xtend.lib.gwt;2.8.3: not found
[error] (*:update) sbt.ResolveException: unresolved dependency: org.eclipse.xtend#org.eclipse.xtend.lib;2.8.3: not found
[error] unresolved dependency: org.eclipse.xtend#org.eclipse.xtend.lib.gwt;2.8.3: not found
[error] Total time: 12 s, completed 24/03/2017 1:54:11 PM</pre><br/>See complete log in <a href="file:/Users/ringo/Library/Logs/IdeaIC2017.1/sbt.last.log">file:/Users/ringo/Library/Logs/IdeaIC2017.1/sbt.last.log</a>

**Comment by javadelight** [comment]
Thank you for reporting the issue.

Are you using Maven Central (I think it should be the default in SBT but maybe it's changed for your project)?

Otherwise, could you add the following dependency directly to your project and see if it would resolve?

https://mvnrepository.com/artifact/org.eclipse.xtend/org.eclipse.xtend.lib/2.8.3

**Comment by workingDog** [comment]
did not work with   "org.eclipse.xtend" % "org.eclipse.xtend.lib" % "2.8.3"

but worked (i.e. compile) with:
libraryDependencies ++= Seq(
  "org.eclipse.xtend" % "org.eclipse.xtend.lib.gwt" % "2.11.0",
  "org.eclipse.xtend" % "org.eclipse.xtend.lib" % "2.11.0",   
  "org.javadelight" % "delight-nashorn-sandbox" % "0.0.8")

I'm using Intellij to try to compile from source without success yet, it seems to be specific to eclipse.

P.S
is it possible to get an invocable from the sandbox?

**Comment by mxro** [comment]
Hmm, that's strange. Well, I've updated the dependency in the library to that version. Does it work now for you without specifying the extra dependency?

What are the problems in compiling from source in Intellij? It should work, I think ...

**Comment by workingDog** [comment]
First, thanks for taking the time to look into this. 
A great project BTW.

Without publishing a new library to maven, my setup
libraryDependencies += "org.javadelight" % "delight-nashorn-sandbox" % "0.0.8"
will just get that version from maven. 

So, no it does not work without including the extra dependencies:
libraryDependencies ++= Seq(
"org.eclipse.xtend" % "org.eclipse.xtend.lib.gwt" % "2.11.0",
"org.eclipse.xtend" % "org.eclipse.xtend.lib" % "2.11.0",
"org.javadelight" % "delight-nashorn-sandbox" % "0.0.8")

With regards to compiling from source, I get a jar file,
but somehow it does not work when I run my project, something to do with the manifest signature.
It could be just my setup, however it works well with other jar files.
This is the error I get:

java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
        at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:314)
        at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:268)
        at java.util.jar.JarVerifier.processEntry(JarVerifier.java:316)
        at java.util.jar.JarVerifier.update(JarVerifier.java:228)
        at java.util.jar.JarFile.initializeVerifier(JarFile.java:383)
        at java.util.jar.JarFile.getInputStream(JarFile.java:450)
        at sun.misc.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:977)
        at sun.misc.Resource.cachedInputStream(Resource.java:77)
        at sun.misc.Resource.getByteBuffer(Resource.java:160)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:454)

**Comment by javadelight** [comment]
That's true :)

Just released version 0.0.9 to Maven Central. Could you try with that version?

---

So for the compilation from source, you can compile a JAR file from the library but then when you want to **use** the JAR file you get the error?

Are you trying to create a 'fat jar' file with Maven shade plugin?

**Comment by workingDog** [comment]
I tried using: "org.javadelight" % "delight-nashorn-sandbox" % "0.0.9"
this did not work, I still get: org.eclipse.xtend#org.eclipse.xtend.lib.gwt;2.8.3: not found

I think this is because the following depend on it:
 "org.javadelight" % "delight-async" % "0.1.0"
 "org.javadelight" % "delight-functional" % "0.0.10"

This works:
  "org.eclipse.xtend" % "org.eclipse.xtend.lib.gwt" % "2.11.0",
  "org.eclipse.xtend" % "org.eclipse.xtend.lib" % "2.11.0",
  "org.javadelight" % "delight-nashorn-sandbox" % "0.0.9"

Re: the jar file, my fault, I was using Intellij to "build" the jar.
Using maven, I can produce a jar file that works;
delight-nashorn-sandbox-0.0.9-SNAPSHOT.jar

In my project, replacing the dependencies with the jar file works.

**Comment by mxro** [comment]
That's strange! I must have made a mistake with the dependencies somewhere! I reuploaded everything now for version 0.0.10.

Unfortunately, I had to reduce the version for the xtend dependency to 2.10.0 because of [this issue](https://github.com/eclipse/xtext-lib/issues/40).

**Comment by workingDog** [comment]
that has fixed the problem. Thanks very much.
I can now use just: 
"org.javadelight" % "delight-nashorn-sandbox" % "0.0.9"

**Comment by mxro** [comment]
Awesome :) Thank you for checking it & I'm closing this issue now!
