### ISSUE TITLE
question on argument passing

### ISSUE THREAD

**Issue by workingDog** [javadelight/delight-nashorn-sandbox#17]
How do I pass an argument to a function using a sandbox?

With the ScriptEngine, I had something like:

  val engine = new ScriptEngineManager().getEngineByName("nashorn")
  val invocable = engine.asInstanceOf[Invocable]
  engine.eval(theJavaScript)
  invocable.invokeFunction("filter", data)
  
  where theJavaScript = "function filter(data) { ... }"

How to I do the same within a sandbox?
 
 val sandbox = NashornSandboxes.create
 sandbox.eval(theJavaScript)
 // then how do I run "filter" with my data, or pass data to theJavaScript

**Comment by mxro** [comment]
Good question!

You can get a handle of the function easily either by using NashornSandbox.get() or NashornSandbox.eval(). You just need to cast the returned object to ScriptObjectMirror.

I've added a example/test to the project:

https://github.com/javadelight/delight-nashorn-sandbox/blob/2f740ffa7bff3554be2e22e6bc3a761c066ba80c/src/test/xtend/delight/nashornsandbox/tests/TestAccessFunction.xtend

Does this answer your question?

**Comment by workingDog** [comment]
great. It worked well. Thanks.

**Comment by javadelight** [comment]
Thank you for your answer. Closing this issue now!
