### ISSUE TITLE
It is almost impossible to extend the class NashornSandBoxImpl

### ISSUE THREAD

**Issue by marcgemis** [javadelight/delight-nashorn-sandbox#19]
Almost all member variables in NashornSandBoxImpl are private and no getters are available.
This makes it impossible to overwrite some methods that need access to those member variables.

**Comment by mxro** [comment]
Thank you for submitting the issue report.

That is a good point. I've changed all the member variables and private methods to `protected`. Could you have a look at the commit if that would resolve your issue?

**Comment by marcgemis** [comment]
I see no reason why it wouldn't work, see fine to me.

**Comment by mxro** [comment]
Awesome :) Closing this issue now then!

**Comment by abonstu** [comment]
**Again**, all member variables have been reverted to private with no getters available making this class impossible to extend!

**Comment by javadelight** [comment]
All member variables are changed to **protected** again. This is deployed to Maven central in version 0.1.1.
