### ISSUE TITLE
Missing dependency on delight-async

### ISSUE THREAD

**Issue by smillies** [javadelight/delight-nashorn-sandbox#2]
got interested in this and tried to compile, but there is something wrong with the dependencies. Where can I find

```
<dependency>
	<groupId>org.javadelight</groupId>
	<artifactId>delight-async</artifactId>
	<version>0.0.9</version>
</dependency>Where can I find
```
or has this been replaced with something else?

--Sebastian

**Comment by javadelight** [comment]
Sorry, the dependencies were not completely built. They should be now.

All dependencies are in the following repository:

    <repository>
        <id>Appjangle Releases</id>
        <url>http://maven.appjangle.com/appjangle/releases</url>
    </repository>

So adding this under <repositories> in the pom should allow you to build the project (it should already be included in the pom).

Let me know if there are any further issues!
