### ISSUE TITLE
Insertion of intCheckForInterruption et al. at the top breaks the line numbers in stacktraces

### ISSUE THREAD

**Issue by marcgemis** [javadelight/delight-nashorn-sandbox#20]
The evaluated JavaScript code is prefixed with some variable declarations and the definition of the intCheckForInterruption function. This moves the original code several lines down. Stacktraces generated by running the code will point to the wrong line.

I fixed this locally by removing all the new lines in NashornSandBoxImpl.eval.run
Now the extra code is added to the first line of original JavaScript code.

This is important to report the error back to the submitter of the code (who is not aware of all fiddling to make the code interruptible)

**Comment by mxro** [comment]
Yes, that is a good point.

I've changed the way the code is generated that it inserts as few newlines as possible. 

However, it still beautifies the code before additional statements are injected, which can mess with the line numbers.

To allow for easier debugging of such problems, I've added a debug mode, which will output the generated JS (`sandbox.setDebug(true);`)

Do you think this sufficiently addresses the issue?

**Comment by marcgemis** [comment]
The beautifying is no problem, as we show the beautified code to our users anyhow.
I'll try to integrate your fix into our code ASAP and let you know the results.

**Comment by mxro** [comment]
Closing this issue for now. If any code is not handled correctly, please be welcome to open a new issue!
