### ISSUE TITLE
setWriter function removed?

### ISSUE THREAD

**Issue by philipborg** [javadelight/delight-nashorn-sandbox#21]
I pushed for a setWriter function that was added but for some reason removed later on in this commit.
https://github.com/javadelight/delight-nashorn-sandbox/commit/7cab5e88d7833267588858eaaa03066fb31865b0
Why? I don't see why that function would cause any harm and it is rather usable. No new functionality has been added to replace it neither as far as I know. @mxro

**Comment by mxro** [comment]
Yes, sorry I don't know exactly why it was removed. Maybe it wasn't in the Xtend sources and thus when the source code was generated again (*.xtend -> *.java).

It is now added back in in version 0.0.12 which I've just published to Maven Central.

**Comment by philipborg** [comment]
Ah so that was the reason, I was mostly just a bit confused. Thanks :grin:
