### ISSUE TITLE
Runtime exception on setting cpu and memory restrictions.

### ISSUE THREAD

**Issue by appyschool** [javadelight/delight-nashorn-sandbox#27]
I am consuming this library in a servlet container and it is always throwing the below error on call.

java.lang.RuntimeException: javax.script.ScriptException: SyntaxError: empty range in char class in <eval> at line number 1
	at delight.nashornsandbox.internal.JsSanitizer.assertScriptEngine(JsSanitizer.java:124)
	at delight.nashornsandbox.internal.JsSanitizer.<init>(JsSanitizer.java:114)
	at delight.nashornsandbox.internal.NashornSandboxImpl.getSanitizer(NashornSandboxImpl.java:172)
	at delight.nashornsandbox.internal.NashornSandboxImpl.eval(NashornSandboxImpl.java:117)

sandbox = NashornSandboxes.create();
		sandbox.setMaxCPUTime(100);
		sandbox.setMaxMemory(50 * 1024);
		sandbox.allowNoBraces(false);
		sandbox.setMaxPerparedStatements(30); // because preparing scripts for
												// execution is expensive
		sandbox.setExecutor(Executors.newSingleThreadExecutor());

in servlet doGet () {

---
sandbox.eval("function callMe() { return 42; };");
			final Object _get = sandbox.get("callMe");
---
}

**Comment by mxro** [comment]
Hello There! Thank you for reporting this issue.

Could you have a look at [this test case](https://github.com/javadelight/delight-nashorn-sandbox/blob/d19eeeab22efa109f337f7b34e7ef687ce2d63ba/src/test/java/delight/nashornsandbox/TestGetFunction.java)?

I tried to recreate what you are describing. Is the test set up correctly? If I run it, the test succeeds.

**Comment by appyschool** [comment]
All the test cases which have cpu or memory monitoring are failing. I have gone through the code and with below changes both test cases and my code is working.

JsSanitizer.java

Line number : 244

 try(final BufferedReader reader = new BufferedReader(new InputStreamReader(
            new BufferedInputStream(JsSanitizer.class.getClassLoader().getResourceAsStream(BEAUTIFY_JS)), **"UTF8"**))) {
          final StringBuilder sb = new StringBuilder();
          String line;
          while ((line=reader.readLine()) != null) {
            sb.append(line).append('\n');
          }
          script = sb.toString();
        }

**Comment by mxro** [comment]
That's very interesting! I don't see why specifying the encoding should cause any problems here, so I have added the parameter and released a new version 0.1.4 with this fix to Maven central. Does this solve your issue?

**Comment by appyschool** [comment]
Yes, fix is working for me now. Thanks for a quick turnaround.

**Comment by mxro** [comment]
That's great! I will close this issue now. If it comes up again, please be free to reopen or submit a different issue!
