### ISSUE TITLE
ScriptContext support for nashorn

### ISSUE THREAD

**Issue by srinivasarajuch** [javadelight/delight-nashorn-sandbox#28]
Hi,

Currently, this library is providing option to  set java object as a JS global variable. It is not giving an option to set ScriptContext, which is very useful feature form nashorn library to  scoping the script execution as below

 ScriptEngineManager manager = new ScriptEngineManager();
        ScriptEngine engine = manager.getEngineByName("nashorn");

 // define a different script context
        ScriptContext newContext = new SimpleScriptContext();
        newContext.setBindings(engine.createBindings(), ScriptContext.ENGINE_SCOPE);
        Bindings engineScope = newContext.getBindings(ScriptContext.ENGINE_SCOPE);

        // set the variable to a different value in another scope
        engineScope.put("x", "world");

        // evaluate the same code but in a different script context (x = "world")
        engine.eval("print(x)", newContext);

It would be very helpful if you expose the option to set the script context

**Comment by srinivasarajuch** [comment]
I have created pull request with the above changes. Please review it.

https://github.com/javadelight/delight-nashorn-sandbox/pull/29

**Comment by javadelight** [comment]
Thank you! The PR is included in the latest released version 0.1.5 which will be available in Maven Central shortly.
