### ISSUE TITLE
Move methods to builder / throws exception

### ISSUE THREAD

**Issue by vmichalak** [javadelight/delight-nashorn-sandbox#33]
Hi all,

First of all, thanks for your work on this library. I found some advice on how to make a robust sandbox for Nashorn here.

On the `NashornSandboxImpl` class, all `allowXXXFunction()` methods cannot be called after first `eval()`. To simplify library usage it could be cool to move theses methods to a builder or, at least, throws an exception to alert user of his mal-usage.

When we reach a consensus, if anyone are ok, I will implement it.

**Comment by mxro** [comment]
Hi Valentin, 

Thank you for raising this issue. That is a good point!

I think it would be best not to change the API of the `NashornSandbox` thus I've added that exceptions are thrown if these properties are set after `eval` has been called. Do you think it would work this way?

(and sorry I didn't read your message carefully enough and missed your offer to implement it - please be welcome to refine what I have committed so far - I am not a 100% happy these properties are handled and I am sure there is a more elegant solution for this!)

**Comment by vmichalak** [comment]
It seem's good :) Thanks you
