### ISSUE TITLE
Script failing with invalid syntax error

### ISSUE THREAD

**Issue by srinivasarajuch** [javadelight/delight-nashorn-sandbox#47]
Below script execution is failing

function preProcessor()
{ 
   serviceInputParams.put("inputparam", " for "); 
}
preProcessor();

Error :
JavaScript. Cause: No block braces after function|for|while|do. Found [for \");\n}
\npreProcessor();

Looks like "for" keyword is identified even it is code.

**Comment by mxro** [comment]
Thank you for reporting this issue!

This has been fixed in is included in the latest version 0.1.13 - which has just been uploaded to Maven Central. Does this fix your issue?

**Comment by srinivasarajuch** [comment]
Fix is working for me, so closing the issue.
