### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by eduveks** [javadelight/delight-nashorn-sandbox#5]
Hi!

The errors in scripting is not catchable, like:

`nashornSandbox.eval("blah_blah_blah();");`

None exceptions can be handle!

Maybe a solution like:

`nashornSandbox.getException()`

Will be very useful!

Is a nightmare working without log of bad coding.

Thank you.

**Comment by mxro** [comment]
Thank you for submitting the issue.

Sorry but I don't know what you are referring to.

I just added another test case - it shows that exceptions are thrown from the code. You can handle them if you catch them. Or does this not work in your case?

You can see the test case here:
**Xtend**: https://github.com/javadelight/delight-nashorn-sandbox/blob/master/src/test/xtend/delight/nashornsandbox/tests/TestExceptions.xtend
**Java**: https://github.com/javadelight/delight-nashorn-sandbox/blob/master/src/test/java/delight/nashornsandbox/tests/TestExceptions.java

**Comment by eduveks** [comment]
Thank you by your fast reply.

But I'm using like this:

```
nashornSandbox = NashornSandboxes.create();
nashornSandbox.setMaxCPUTime(100);
nashornSandbox.setExecutor(Executors.newSingleThreadExecutor());
```

As a thread is launched the exception is "invisible".

In some of your test case is missing the "Thread Mode"!

**Comment by mxro** [comment]
Thanks for the clarification. I've changed the code - now the exception should show up. 

This is all in the latest version 0.0.4 on the maven repo and in the source code.

Could you have a look if it throws the exception for you now?

**Comment by eduveks** [comment]
Solved! Works like a charm!

Thank you!
