### ISSUE TITLE
Restricted to return only one object!

### ISSUE THREAD

**Issue by eduveks** [javadelight/delight-nashorn-sandbox#6]
Will be great if possible grab any global variable of the script.

As is possible using the native ScriptEngine of the Nashorn.

`Object scriptVar = engine.get("any_variable");`

With NashornSandbox this is impossible!

An idea:

```
nashornSandbox.extract("my_script_var");
nashornSandbox.eval("my_script_var = 1;");
Object myScriptVar = nashornSandbox.get("my_script_var");
nashornSandbox.clean();
```

With this solution will be able to say first each variable the ScriptEngine inside the thread need to collect in an Map.

And an method to clear the Map to prevent memory usage with trash.

**Comment by mxro** [comment]
Can you get it like this?

    Object myScriptVar = nashornSandbox.eval("my_script_var");

**Comment by eduveks** [comment]
Can suit to few variables to catch.

But if is need catch 100 variables or more... maybe has a bad performance because the interpretation/parse/execution.

But I can survive because I need only 4 on max! :D

And still a big issue!

I found the problem... 

```
	override NashornSandbox allow(Class<?> clazz) {
		allowedClasses.add(clazz.name)
		scriptEngine = null
		this
	}
	
	override NashornSandbox inject(String variableName, Object object) {
		this.globalVariables.put(variableName, object)
		allow(object.class)
		this
	}
```

In the method ALLOW you is making the **scriptEngine equals null**!

```
Object myScriptVarOK = nashornSandbox.eval("my_script_var = 1;");
nashornSandbox.inject("a", "1");
Object myScriptVarNOK = nashornSandbox.eval("my_script_var");
```

Because the method INJECT mode is calling the method ALLOW and the scriptEngine is turned into null! As scriptEngine being null a new one will be created without the variable!

**Comment by mxro** [comment]
Good point re setting the script engine to null.

I now changed it to:

    if (scriptEngine != null) {
			throw new IllegalStateException("eval() was already called. Please specify all classes to be allowed before calling eval()")
		}

So an exception will be thrown if you call allow() after eval() - that's the only way to do it (since the allowed classes need to be known during creation of the script engine).

**Comment by eduveks** [comment]
Is required call the ALLOW when call the INJECT ?

This brings a limitation, will be impossible to share 2 evals with a inject between!

The NashornSandbox will be limited to only INJECT before the eval and never between evals! This is very restrict...

**Comment by mxro** [comment]
Added method .get on NashornSandbox that can be used to obtain variable values. Does that work for you.

INJECT calls allow implicitly (since the class needs to be allowed before it is injected). However, I added an exception that you can inject variables even after the first eval IF the classes of these variables have been ALLOWED before.

That's the best I can think of - does that work for you?

**Comment by eduveks** [comment]
I think I have a better solution to suggest...

In **NashornSandboxImpl**:
...
	*** val Set<String> allowedClasses *** REPLACE THIS WITH:
	var SandboxClassFilter sandboxClassFilter  // ADD
...
			scriptEngine = factory.getScriptEngine(sandboxClassFilter);
...
	override NashornSandbox allow(Class<?> clazz) {
		sandboxClassFilter.add(clazz.name)
		this
	}
	override NashornSandbox inject(String variableName, Object object) {
		this.globalVariables.put(variableName, object)
		if (!sandboxClassFilter.contains(object.class.name)) {
			allow(object.class)
		}
		if (scriptEngine != null) {
			scriptEngine.put(variableName, object)
		}
		this
	}
...

In **SandboxClassFilter**:

```
	def void add(Set<String> allowed) {
		allowed.add()
	}
        def boolean contains(String className) {
		allowed.contains(className)
	}
	new() {
		this.allowed = new HashSet()
	}
```

By this way I think will be able to inject at any time and the allow calls will be more dynamic, and the order of calls of evals and injects will not matter anymore.

Right?

**Comment by mxro** [comment]
Okay I see I think this could work. But looks like a bigger job, so that should be something for the next version!

**Comment by eduveks** [comment]
I made these changes:

https://github.com/eduveks/delight-nashorn-sandbox/commit/f5ca8ced6bb8d57daac819697670bbe13ef20550

Hope you like 😄

**Comment by mxro** [comment]
All fixed in Pull Request! Thank you! :smile:
