### ISSUE TITLE
Missing artifact com.sun:tools:jar:1.4.2 on Java 10

### ISSUE THREAD

**Issue by gschnepp** [javadelight/delight-nashorn-sandbox#62]
Max,

building a project with proxy-vole library which has switched from javadelight-rhino-sandbox to javadelight-nashorn-sandbox recently, I get above error message on Maven (m2e) with Java 10. That's due to Java 10 has no file tools.jar any longer (Java 8 has this system dependency).

1. Does nashorn-sandbox need this dependency?
2. What's with updating this fairly updated version 1.4.2 to any actual one?

Your current dependency in POM:

> 		<dependency>
> 			<groupId>com.sun</groupId>
> 			<artifactId>tools</artifactId>
> 			<version>1.4.2</version>
> 			<scope>system</scope>
> 			<systemPath>${java.home}/../lib/tools.jar</systemPath>
> 		</dependency>

Proxy-vole also has implemented slf4j api with latest version, one thing I've read here is under discussion of removing. I'd stay with it... ;-)

Kind regards
Guido

**Comment by gschnepp** [comment]
For reference: https://github.com/MarkusBernhardt/proxy-vole/issues/48

**Comment by MarkusBernhardt** [comment]
Hi Guido,

sorry, I have so far never installed Java 10. Think I should do that.

One more thing because of the slf4j api. The code still does not use slf4j or any other logging library. I only added a default implementation for my logging interface based on slf4j. Many new users struggled there in the first place.

When you want to get rid of the dependency you can use your own implementation and remove the slf4j dependencies.

Kind regards,
Markus

**Comment by gschnepp** [comment]
Yes, you should try with Java 10 or 11 which is on its way already. You'll see a lot of drawbacks from the new module system where this or that is not working anymore in your apps until you activate the correct module set. (I had the case with a standard desktop app not sending e-mails any longer, silently without messages). With good support from the publisher I found the problem: His application now has to run with the javax.activation module (containing javax.mail.*) activated, not only the basic set). Java world's getting complicated.

I don't really need slf4j, but it's not a problem for me, too, since my backend already has support for it. This may be different with other users now having a new dependency. But that's also true for javadelight-nashorn-sandbox and its crappy outdated old com.sun:tools dependency. Have you read that Oracle tends to remove Nashorn from code if no one else takes it (https://www.i-programmer.info/news/80-java/11895-oracle-says-drop-nashorn-from-jdks.html)? **So standing with javadelight-rhino-sandbox  may not be such a bad idea, if nashorn will be deprecated in near future.**

Guido

**Comment by mxro** [comment]
Hi Guido, 

Thank you for reporting this issue. The tools.jar dependency is required for running the tests on travis-ci.

So do I understand it correctly that updating it to a newer version would not resolve the issues (e.g. that it doesn't build?)

**Comment by gschnepp** [comment]
Correct, I'd say, since this tools.jar is not available anymore with Java 9+, expecially not in this hardcoded place (../lib/tools.jar). Internal routines may be placed anywhere else or accessible by --add-modules {someModule}, but I don't know.

You could mark this dependency as <scope>test</scope> if it's necessary for testing only. It would not break builds on newer Java versions then. Well, should not. Have not tested it right now. But a replacement is necessary mid-term anyway, I think.

**Comment by mxro** [comment]
Okay! Hmm, I don't think it is possible to make a dependency `<scope>system</scope>` and `<scope>test</scope>` at the same time.

I have removed the dependency now and it still seems to work in the travis-ci build. (It might have failed in a Jenkins build this project is also going through but I will look at that later.)

The changed version is released as 0.1.16 to Maven Central.

**Comment by gschnepp** [comment]
Thanks for your support! It's there and building works again. Closing.

**Comment by gsmachado** [comment]
Hello @gschnepp,
Any idea when this fix would be pushed to a release/version?
Cheers.

**Comment by gschnepp** [comment]
javadelight-nashorn-sandbox version 0.1.16 is on Maven already! You can add your own dependency for it to your POM to use it with proxy-vole 1.0.5. Maven will take the newest (0.1.16 instead 0.1.15 in proxy-vole) in this case.

Regards
Guido
