### ISSUE TITLE
Nashorn Engine is not exit

### ISSUE THREAD

**Issue by kaelky** [javadelight/delight-nashorn-sandbox#65]
I set the max cpu time for 10 seconds. After 10 seconds, the execution of my script is not stopped while my %CPU usage  is 0.0 (stopped). Can you help me to solve this issue,  please?

**Comment by mxro** [comment]
Hi @kaelky 

Could you provide the code you are using for your test? Thank you!!

**Comment by kaelky** [comment]
Hello sir.

This I attach my code

Main.java

ScriptRunner runner = new ScriptRunner("scripts.js");
runner.run();
System.out.println("Hehe");


scripts.js

function sleep(seconds){
    var e = new Date().getTime() + (seconds * 1000);
    while (new Date().getTime() <= e){
    }
}

var counter = 1;
while (true){
    print(counter);
    counter += 1;
    sleep(1);
}


ScriptRunner.java

package com.eksperimental.nonfunctional;

import delight.nashornsandbox.NashornSandbox;
import delight.nashornsandbox.NashornSandboxes;
import org.springframework.core.io.ClassPathResource;

import javax.script.ScriptException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.concurrent.Executors;

public class ScriptRunner implements Runnable {
    private String script;
    private File file;

    public ScriptRunner(String script) throws IOException {
        this.script = script;
        this.file = new ClassPathResource(script).getFile();
    }

    /**
     * Run the script with Nashorn in sandbox
     * NOTES :
     * - MaxCPUTime to run the script is 100MB
     * - MaxExecutionTime to run the script is 10s
     */
    @Override
    public void run(){

        NashornSandbox sandbox = NashornSandboxes.create();
        sandbox.setMaxCPUTime(10000);
        sandbox.setMaxMemory(100000000);
        sandbox.allowNoBraces(false);
        sandbox.setExecutor(Executors.newSingleThreadExecutor());

        try {
            sandbox.eval(scriptToString());
        }
        catch (ScriptException e) {
            e.printStackTrace();
        }
    }

    public String scriptToString() {
        StringBuilder scriptInString = new StringBuilder();

        try (BufferedReader reader = new BufferedReader(new FileReader(file))){
            String currentLine;

            while ((currentLine = reader.readLine()) !=  null){
                scriptInString.append(currentLine).append("\n");
            }
        }
        catch (FileNotFoundException e) {
            System.out.println("File tidak ditemukan");
        }
        catch (IOException e) {
            e.printStackTrace();
        }

        return scriptInString.toString();
    }
}


What I want to do is to kill the thread when the thread has been executing
for too long. But, the thread can't be stop, it just throw an exception I
thought. Here the result of the executing program

[image: Screen Shot 2018-07-30 at 18.08.29.png]

When I want to close the program, it ask me to terminate which is the
program is still running.
[image: Screen Shot 2018-07-30 at 18.09.39.png]
How if I want to really stop the execution of the scripts if exceeded the
memory or time of execution?

Best Regards,
Ricky Chandra Johanes
Universitas Indonesia

Pada tanggal Sab, 28 Jul 2018 pukul 11.19 Max Rohde <
notifications@github.com> menulis:

**Comment by mxro** [comment]
Hi @kaelky 

Thank you for providing the code! I think I see now what your problem is! The MaxCPUTime relates to time the CPU actually does things. So a script could run for very long but use very little CPU time OR run for short and use a lot of CPU time - just depending on how CPU intensive the operations are. 

Your script looks like it spends a lot of time *sleeping* - which uses very little CPU, that's why the sandbox does not interrupt the execution. Does that make sense? Hope this answers your question!

**Comment by kaelky** [comment]
Hello, Mr. Max

Now, I don't think so that the sandbox does not interrupt the execution
now. When I tried to allow the print function, I saw that the script
execution was stopped (the print was stopped), but the program is still
running. So, I think that the ThreadMonitor thread that was running, not
the script execution. How about that? Does that make sense?

If your answer is Yes, I think I need help to stop the ThreadMonitor
execution now.

Best Regards,
Ricky Chandra Johanes

Pada tanggal Rab, 1 Agt 2018 pukul 15.19 Max Rohde <notifications@github.com>
menulis:

**Comment by FRosner** [comment]
@kaelky make sure to execute `sandbox.getExecutor().shutdown();` after you are done. Maybe your script has finished but the JVM is still waiting for the executor to shut down (which won't happen unless you tell it to?

**Comment by mxro** [comment]
@kaelky Hope your question is resolved by FRosner's comment? Thanks @FRosner for helping out 🥇

**Comment by kaelky** [comment]
That's work. Thanks for helping @FRosner @mxro
