### ISSUE TITLE
Eval with bindings ignoring allowExitFunctions(false) settings

### ISSUE THREAD

**Issue by everestbt** [javadelight/delight-nashorn-sandbox#67]
While trying to wire this up I found an issue with `allowExitFunctions(false)`. When this is set and then `eval(String js,Bindings bindings)` is called, for example for the script "quit()" it will exit the JVM, counterposed to the intent of the setting. 

This appears to be due to the bindings overwriting the original settings. I am not very familiar with Nashorn so my assumptions of the impact of `Bindings` and the persistence of these methods could be false. For usability I believe it would be helpful that, regardless of `Bindings` the settings are applied.

**Comment by everestbt** [comment]
Opened https://github.com/javadelight/delight-nashorn-sandbox/pull/68.

**Comment by everestbt** [comment]
This appears to impact all function limitations enforced by bindings, i.e. `allowPrintFunctions(false)` does not enforce when custom bindings are passed in.

**Comment by mxro** [comment]
Thanks heaps for the pull request. This is all merged now and published with version 0.1.17! Is the issue resolved now?

**Comment by everestbt** [comment]
@mxro Thanks for merging it in. I have been working on optimising the fix a little more, I have a bit more testing to do on this but by Tuesday I should have an improved fix on a pull request.

**Comment by mxro** [comment]
@everestbt That sounds awesome! Looking forward to the fix - will do my best to merge it in faster this time 😃

**Comment by everestbt** [comment]
@mxro I have introduced a pull request #69 which I think improves things, by removing the extra evaluations by instead caching a set of secured bindings. Take a look and let me know your thoughts, happy to address any comments.

**Comment by mxro** [comment]
Version 0.1.18 released to Maven Central including this fix. Let me know if there is anything else to be done for this issue, otherwise we can close. Thank you for fixing this 👍

**Comment by everestbt** [comment]
Great, do you want me to open another issue in relation to ScriptContext having the same issue, there is an ignored test indicating this in the testExit:
`@Test
 @Ignore("This will fail as there is no confirmation on Script Contexts")
  public void testQuitWithScriptContext() throws ScriptCPUAbuseException, ScriptException {
    final NashornSandbox sandbox = NashornSandboxes.create();
    sandbox.eval("quit();", new SimpleScriptContext());
  }`

**Comment by mxro** [comment]
Yes please :)

**Comment by everestbt** [comment]
I have opened #70. Closing this as resolved.
