### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by eduveks** [javadelight/delight-nashorn-sandbox#7]
Execute this code:

`nashornSandbox.eval("exit();");`

And the result will be SAYONARA!

To prevent this with some investigations I made this script to "pre-eval" and jail:

```
nashornSandbox.eval("\n" +
                "quit = function() {};\n" +
                "exit = function() {};\n" +
                "\n" +
                "print = function() {};\n" +
                "echo = function() {};\n" +
                "\n" +
                "readFully = function() {};\n" +
                "readLine = function() {};\n" +
                "\n" +
                "load = function() {};\n" +
                "loadWithNewGlobal = function() {};\n" +
                "\n" +
                "Java = null;\n" +
                "org = null;\n" +
                "java = null;\n" +
                "com = null;\n" +
                "sun = null;\n" +
                "net = null;\n" +
                "\n" +
                "$ARG = null;\n" +
                "$ENV = null;\n" +
                "$EXEC = null;\n" +
                "$OPTIONS = null;\n" +
                "$OUT = null;\n" +
                "$ERR = null;\n" +
                "$EXIT = null;\n" +
                "");
```

Will be great if this project brings this by default.

**Comment by mxro** [comment]
Perfect! Thanks for this - the code is executed automatically in the sandbox. Though I guess the object `Java` is required, so I left that in.

Does this solve the issue for you?

**Comment by eduveks** [comment]
Thank you!

These variables as NULL maybe is unnecessary because you already locks the access to packages:
```
...
"Java = null;\n" +
"org = null;\n" +
"java = null;\n" +
"com = null;\n" +
"sun = null;\n" +
"net = null;\n" +
...
```

For me is perfect! But to others maybe is better have a way to allow some functions can be used.

```
nashornSandbox.setAllowPrintFunctions(true);   // print & echo
nashornSandbox.setAllowReadFunctions(true);   // readLine & readFully
nashornSandbox.setAllowLoadFunctions(true);   // load & loadWithNewGlobal
nashornSandbox.setAllowExitFunctions(true);  // quit & exit
nashornSandbox.setAllowGlobalsObjects(true);  // $ARG, $ENV, $EXEC, $OPTIONS, $OUT, $ERR, $EXIT
```

See here to more details:

https://docs.oracle.com/javase/8/docs/technotes/guides/scripting/nashorn/shell.html

I think this will be perfect to everyone control their needs.

**Comment by mxro** [comment]
Yes I think you are right, I removed the NULL variables for the packages.

Re the additional API to allow access to Nashorn built in functions. Good idea! That should be something for the next version as well.

**Comment by eduveks** [comment]
I already made this...

https://github.com/eduveks/delight-nashorn-sandbox/commit/f5ca8ced6bb8d57daac819697670bbe13ef20550

I did not make the unit tests yet to this... but I'm certain that works!

**Comment by mxro** [comment]
Hi! Looks great! Thank you! Can you make a pull request?

**Comment by mxro** [comment]
Fixed with Pull Request [9](https://github.com/javadelight/delight-nashorn-sandbox/pull/9). Thank you!
