### ISSUE TITLE
All JARs with one click!

### ISSUE THREAD

**Issue by eduveks** [javadelight/delight-nashorn-sandbox#8]
The JVM can run inside others technologies like NodeJS, PHP, Python, Ruby, etc...

Is a nightmare to a developer of other technologies work with Maven, because Maven is the worst tool compared with others, because is the more complex. For example, NPM, Artisan, EGG, GENS and etc... are much much much more easy to work than Maven.

I know the build in Java is more complex, but is too complex like .Net, and in .Net the NuGets is much more simple than the Maven!

I don't understand why many Java projects don't have the jars easy to download!

All the XTEND projects to instal only has the Maven instructions, is ridiculous!

And to not say about people that only use the JRE or even don't have the Maven installed will be forced to install only to build a little JAR. Think in time spent only to build a simple JAR.

Like the Hibernate projects has a ZIP with all JARs and dependencies to download and start to play! Is very very simple!

I strongly suggest to more people can use this project you can put the main Jar and the dependencies of org.eclipse.xtext.***.jar easy to download.

Is just a suggest that I think is very useful to non Java pros and non Maven experts.

**Comment by mxro** [comment]
Yeah, I agree it should be easier to get a single JAR from a Maven dependency.

I've added a compiled JAR [here](https://github.com/javadelight/delight-nashorn-sandbox/releases).

Does this work for you?

**Comment by eduveks** [comment]
Very nice!

Thank you! ;)

**Comment by mxro** [comment]
Perfect. I uploaded the new version 0.0.5 with your additions too. If you would like, I will be happy to add your name to the README as a contributor for the project!

**Comment by eduveks** [comment]
Ok! Thank you!
This project is now part of one of main solutions in my company. And if I face a new issue then I will collaborate fast. This project is now under my eyes too, with pleasure.
Thank you again by your attention and opening to make good changes.
Lets rock 😉

**Comment by mxro** [comment]
That's perfect, I added the section. Thank you for your improvements :smile: and lets keep in touch!
