### ISSUE TITLE
Cannot create sandbox on JVM that does not support ThreadMXBean

### ISSUE THREAD

**Issue by amoravec** [javadelight/delight-nashorn-sandbox#83]
The ThreadMonitor constructor calls `ManagementFactory.getThreadMXBean()`, which on some JVMs native implementation may throw an `UnsupportedOperationException`.

This is blocking usage where not CPU or memory limit is set and the JVM implementation throws and exception creating the `ThreadMXBean `which would otherwise not be needed.

**Comment by mxro** [comment]
PR merged and new version released. Thank you!
