### ISSUE TITLE
Support for GraalJS engine

### ISSUE THREAD

**Issue by mellster2012** [javadelight/delight-nashorn-sandbox#85]
Considering adding this to our fork and submitting a PR when ready. Many if not most of the sandbox features should run on any ScriptEngine and Nashorn has been deprecated  for a while, so we will be eventually switching to GraalVM's JS engine. I don't think we need a separate project for that, rather if we abstract out and refactor slightly we may be able to make this a sandbox which supports multiple engines. This can be done in stages of course.

**Comment by mxro** [comment]
Hi Marco, that sounds like a great idea! I'm sure there are a lots of bits and pieces that can be reused. However, if it becomes too cumbersome we can also fork the project, just let me know!

**Comment by mellster2012** [comment]
I am starting with a simplistic extension of NashornSandboxImpl and see if I can get most if not all tests to pass. Keep in mind that there will be some shortcuts and "hacks" to make some of the tests work, primarily because sharing objects across contexts/bindings is currently not supported in Graal, so we have to use separate engines and/or merge new values into the existing bindings instead of the other way round (see https://github.com/oracle/graal/issues/631). Also class-loading is cached so you need separate engines for separate class-filters. But for the important sandbox features such as interrupt-checking for cpu abuse, runaway scripts, timeouts etc. Graal should work pretty much seamlessly.
cheers

**Comment by mxro** [comment]
Okay, sounds good! Fingers crossed the main features can be easily reused. Otherwise, as said, we can create a fork of this project! So feel free to make breaking changes in the branch if they are necessary!

**Comment by mxro** [comment]
@mellster2012 Should this issue be closed now that there is an initial implementation?

**Comment by mellster2012** [comment]
@mxro Sure let's close it - thx.
