### ISSUE TITLE
Documentation in README about enabling debug output is wrong 

### ISSUE THREAD

**Issue by joelcarranza** [javadelight/delight-nashorn-sandbox#97]
Documentation provides a tip for enabling debug output of transformed JS code using the following modification to log4j.properties file. 

    log4j.logger.delight.nashornsandbox.internal.NashornSandboxImpl=DEBUG

This does not work. `NashornSandboxImpl` uses a logger with different classname. I believe it should be

    log4j.logger.delight.nashornsandbox.NashornSandbox=DEBUG

**Comment by mxro** [comment]
Thank you for raising this issue!

The readme and [log4j.properties](https://github.com/javadelight/delight-nashorn-sandbox/blob/master/src/test/resources/log4j.properties) file have been updated.

Does that look okay now?

**Comment by joelcarranza** [comment]
Yes thank you!
